# ==============================================================================
# 02. Quality control of single-cell RNA-sequencing data
#
# Description:
# This script loads the merged raw Seurat object generated by
# 01_load_and_merge_scRNA_data.R, reconstructs a clean RNA assay from raw counts,
# calculates mitochondrial, ribosomal, and haemoglobin transcript percentages,
# applies prespecified cell-level quality-control thresholds, exports QC
# summaries and diagnostic figures, and saves the filtered Seurat object.
#
# Author:
# Jinjin Zhu
#
# Input:
#   DATA/OUTPUT/merged_raw_Seurat_object.rds
#
# Outputs:
#   DATA/OUTPUT/scRNA_after_QC.rds
#   TABLE/QC/
#   FIGURE/QC/
# ==============================================================================


# 1. Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(tibble)
  library(ggplot2)
  library(patchwork)
})


# 2. Define project paths -------------------------------------------------------

input_file <- "DATA/OUTPUT/merged_raw_Seurat_object.rds"

output_data_dir <- "DATA/OUTPUT"
output_table_dir <- "TABLE/QC"
output_figure_dir <- "FIGURE/QC"

dir.create(
  output_data_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  output_table_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  output_figure_dir,
  recursive = TRUE,
  showWarnings = FALSE
)


# 3. Define QC thresholds -------------------------------------------------------

min_features <- 500
max_features <- 3000
max_counts <- 22000
max_percent_mt <- 10


# 4. Define sequencing-batch information ---------------------------------------

# IMPORTANT:
# Batch labels must describe the actual sequencing or library-preparation batch.
#
# P3 samples were generated in two sequencing batches:
#   batch1: NS_P3_3
#   batch2: LPS_P3_1, LPS_P3_2, NS_P3_1, and NS_P3_2
#
# P7 and P12 samples were generated in batch4 and batch3, respectively.

sample_batch_information <- tribble(
  ~sample_id,  ~batch,

  "LPS_P3_1",  "batch2",
  "LPS_P3_2",  "batch2",
  "NS_P3_1",   "batch2",
  "NS_P3_2",   "batch2",
  "NS_P3_3",   "batch1",

  "LPS_P7_1",  "batch4",
  "LPS_P7_2",  "batch4",
  "NS_P7_1",   "batch4",
  "NS_P7_2",   "batch4",

  "LPS_P12_1", "batch3",
  "LPS_P12_2", "batch3",
  "NS_P12_1",  "batch3",
  "NS_P12_2",  "batch3"
)


# 5. Define helper functions ----------------------------------------------------

get_raw_counts <- function(object) {

  # Seurat v5 may retain one count layer per merged input object. JoinLayers()
  # combines these layers before GetAssayData() is called.
  layer_names <- tryCatch(
    Layers(
      object = object,
      assay = "RNA"
    ),
    error = function(e) {
      character(0)
    }
  )

  count_layers <- grep(
    pattern = "^counts",
    x = layer_names,
    value = TRUE
  )

  if (length(count_layers) > 1) {

    object <- JoinLayers(
      object = object,
      assay = "RNA"
    )
  }

  counts <- tryCatch(
    GetAssayData(
      object = object,
      assay = "RNA",
      layer = "counts"
    ),
    error = function(e) {
      GetAssayData(
        object = object,
        assay = "RNA",
        slot = "counts"
      )
    }
  )

  return(
    list(
      object = object,
      counts = counts
    )
  )
}


summarise_qc <- function(
  object,
  stage
) {

  object@meta.data %>%
    rownames_to_column(
      "cell_barcode"
    ) %>%
    group_by(
      sample_id,
      treatment,
      age,
      group,
      batch
    ) %>%
    summarise(
      stage = stage,
      n_cells = n(),

      median_nFeature_RNA = median(
        nFeature_RNA,
        na.rm = TRUE
      ),
      q1_nFeature_RNA = quantile(
        nFeature_RNA,
        0.25,
        na.rm = TRUE
      ),
      q3_nFeature_RNA = quantile(
        nFeature_RNA,
        0.75,
        na.rm = TRUE
      ),

      median_nCount_RNA = median(
        nCount_RNA,
        na.rm = TRUE
      ),
      q1_nCount_RNA = quantile(
        nCount_RNA,
        0.25,
        na.rm = TRUE
      ),
      q3_nCount_RNA = quantile(
        nCount_RNA,
        0.75,
        na.rm = TRUE
      ),

      median_percent_mt = median(
        percent.mt,
        na.rm = TRUE
      ),
      q1_percent_mt = quantile(
        percent.mt,
        0.25,
        na.rm = TRUE
      ),
      q3_percent_mt = quantile(
        percent.mt,
        0.75,
        na.rm = TRUE
      ),

      median_percent_rb = median(
        percent.rb,
        na.rm = TRUE
      ),
      median_percent_HB = median(
        percent.HB,
        na.rm = TRUE
      ),

      .groups = "drop"
    ) %>%
    relocate(
      stage,
      sample_id,
      treatment,
      age,
      group,
      batch
    )
}


save_plot <- function(
  plot_object,
  file_stem,
  width,
  height
) {

  ggsave(
    filename = file.path(
      output_figure_dir,
      paste0(
        file_stem,
        ".pdf"
      )
    ),
    plot = plot_object,
    width = width,
    height = height,
    units = "in"
  )

  ggsave(
    filename = file.path(
      output_figure_dir,
      paste0(
        file_stem,
        ".tiff"
      )
    ),
    plot = plot_object,
    width = width,
    height = height,
    units = "in",
    dpi = 600,
    compression = "lzw"
  )
}


make_qc_violin_plot <- function(
  object,
  feature_name,
  plot_title
) {

  VlnPlot(
    object = object,
    group.by = "sample_id",
    features = feature_name,
    pt.size = 0,
    raster = FALSE
  ) +
    NoLegend() +
    ggtitle(
      plot_title
    ) +
    theme_classic(
      base_size = 10
    ) +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(
        angle = 45,
        hjust = 1,
        vjust = 1
      ),
      plot.title = element_text(
        hjust = 0.5
      )
    )
}


# 6. Validate batch information -------------------------------------------------

required_batch_columns <- c(
  "sample_id",
  "batch"
)

missing_batch_columns <- setdiff(
  required_batch_columns,
  colnames(sample_batch_information)
)

if (length(missing_batch_columns) > 0) {
  stop(
    "sample_batch_information is missing columns: ",
    paste(
      missing_batch_columns,
      collapse = ", "
    )
  )
}

if (anyDuplicated(
  sample_batch_information$sample_id
)) {
  stop(
    "Duplicated sample IDs were detected in sample_batch_information."
  )
}

if (any(
  is.na(sample_batch_information$batch) |
    sample_batch_information$batch == "" |
    sample_batch_information$batch == "CONFIRM_BATCH"
)) {
  stop(
    "Unconfirmed batch labels remain in sample_batch_information. ",
    "Replace all CONFIRM_BATCH values before running the QC analysis."
  )
}


# 7. Load and validate the merged Seurat object --------------------------------

if (!file.exists(input_file)) {
  stop(
    "Input file does not exist: ",
    input_file
  )
}

merged_seurat <- readRDS(
  input_file
)

if (!inherits(merged_seurat, "Seurat")) {
  stop(
    "The input file must contain a Seurat object."
  )
}

if (!"RNA" %in% Assays(merged_seurat)) {
  stop(
    "The input Seurat object does not contain an RNA assay."
  )
}

required_metadata <- c(
  "sample_id",
  "treatment",
  "age",
  "replicate",
  "group"
)

missing_metadata <- setdiff(
  required_metadata,
  colnames(merged_seurat@meta.data)
)

if (length(missing_metadata) > 0) {
  stop(
    "The merged Seurat object is missing metadata columns: ",
    paste(
      missing_metadata,
      collapse = ", "
    )
  )
}

object_sample_ids <- unique(
  as.character(
    merged_seurat$sample_id
  )
)

missing_batch_assignments <- setdiff(
  object_sample_ids,
  sample_batch_information$sample_id
)

unused_batch_assignments <- setdiff(
  sample_batch_information$sample_id,
  object_sample_ids
)

if (length(missing_batch_assignments) > 0) {
  stop(
    "The following samples have no batch assignment: ",
    paste(
      missing_batch_assignments,
      collapse = ", "
    )
  )
}

if (length(unused_batch_assignments) > 0) {
  warning(
    "The following batch-table samples are absent from the Seurat object: ",
    paste(
      unused_batch_assignments,
      collapse = ", "
    )
  )
}


# 8. Rebuild a clean Seurat object from raw RNA counts -------------------------

raw_data <- get_raw_counts(
  merged_seurat
)

merged_seurat <- raw_data$object
rna_counts <- raw_data$counts

if (nrow(rna_counts) == 0 ||
    ncol(rna_counts) == 0) {
  stop(
    "The raw RNA count matrix is empty."
  )
}

cell_metadata <- merged_seurat@meta.data[
  colnames(rna_counts),
  ,
  drop = FALSE
]

if (!identical(
  rownames(cell_metadata),
  colnames(rna_counts)
)) {
  stop(
    "Cell metadata and the RNA count matrix are not aligned."
  )
}

recalculated_metadata_columns <- intersect(
  c(
    "nCount_RNA",
    "nFeature_RNA",
    "percent.mt",
    "percent.rb",
    "percent.HB",
    "batch"
  ),
  colnames(cell_metadata)
)

cell_metadata <- cell_metadata[
  ,
  setdiff(
    colnames(cell_metadata),
    recalculated_metadata_columns
  ),
  drop = FALSE
]

scRNA <- CreateSeuratObject(
  counts = rna_counts,
  project = "Neonatal_brain_immune_cells",
  meta.data = cell_metadata,
  min.cells = 0,
  min.features = 0
)

rm(
  merged_seurat,
  raw_data,
  rna_counts,
  cell_metadata
)

gc()


# 9. Add verified sequencing-batch metadata ------------------------------------

batch_lookup <- setNames(
  sample_batch_information$batch,
  sample_batch_information$sample_id
)

scRNA$batch <- unname(
  batch_lookup[
    as.character(
      scRNA$sample_id
    )
  ]
)

if (anyNA(scRNA$batch)) {
  stop(
    "Missing batch labels were generated after metadata mapping."
  )
}

sample_order <- sample_batch_information$sample_id[
  sample_batch_information$sample_id %in%
    unique(
      as.character(
        scRNA$sample_id
      )
    )
]

scRNA$sample_id <- factor(
  as.character(
    scRNA$sample_id
  ),
  levels = sample_order
)


# 10. Calculate QC metrics ------------------------------------------------------

mitochondrial_genes <- grep(
  pattern = "^mt-",
  x = rownames(scRNA),
  value = TRUE
)

if (length(mitochondrial_genes) == 0) {
  stop(
    "No genes matching the mouse mitochondrial pattern '^mt-' were found. ",
    "Confirm that mouse gene symbols are used."
  )
}

scRNA[["percent.mt"]] <- PercentageFeatureSet(
  object = scRNA,
  features = mitochondrial_genes
)

ribosomal_genes <- grep(
  pattern = "^Rp[sl]",
  x = rownames(scRNA),
  value = TRUE
)

if (length(ribosomal_genes) == 0) {

  warning(
    "No genes matching the mouse ribosomal pattern '^Rp[sl]' were found."
  )

  scRNA$percent.rb <- 0

} else {

  scRNA[["percent.rb"]] <- PercentageFeatureSet(
    object = scRNA,
    features = ribosomal_genes
  )
}

haemoglobin_genes <- c(
  "Hba-a1",
  "Hba-a2",
  "Hbb-b1",
  "Hbb-b2",
  "Hbe1",
  "Hbg1",
  "Hbg2",
  "Hbm",
  "Hbq1",
  "Hbz"
)

haemoglobin_genes_present <- CaseMatch(
  search = haemoglobin_genes,
  match = rownames(scRNA)
)

haemoglobin_genes_present <- unique(
  haemoglobin_genes_present[
    !is.na(
      haemoglobin_genes_present
    )
  ]
)

if (length(haemoglobin_genes_present) == 0) {

  warning(
    "None of the predefined haemoglobin genes were found."
  )

  scRNA$percent.HB <- 0

} else {

  scRNA[["percent.HB"]] <- PercentageFeatureSet(
    object = scRNA,
    features = haemoglobin_genes_present
  )
}


# 11. Export and visualize pre-QC metrics --------------------------------------

qc_summary_pre <- summarise_qc(
  object = scRNA,
  stage = "Pre-QC"
)

qc_features <- c(
  "nFeature_RNA",
  "nCount_RNA",
  "percent.mt",
  "percent.rb",
  "percent.HB"
)

qc_plots_pre <- lapply(
  qc_features,
  function(feature_name) {

    make_qc_violin_plot(
      object = scRNA,
      feature_name = feature_name,
      plot_title = feature_name
    )
  }
)

pre_qc_panel <- wrap_plots(
  qc_plots_pre,
  ncol = 2
)

save_plot(
  plot_object = pre_qc_panel,
  file_stem = "QC_metrics_before_filtering",
  width = 14,
  height = 10
)


# 12. Visualize the prespecified QC thresholds ---------------------------------

p_feature_threshold <- VlnPlot(
  object = scRNA,
  group.by = "sample_id",
  features = "nFeature_RNA",
  pt.size = 0,
  raster = FALSE
) +
  geom_hline(
    yintercept = c(
      min_features,
      max_features
    ),
    linetype = "dashed"
  ) +
  NoLegend() +
  theme_classic(
    base_size = 10
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    )
  )

p_count_threshold <- VlnPlot(
  object = scRNA,
  group.by = "sample_id",
  features = "nCount_RNA",
  pt.size = 0,
  raster = FALSE
) +
  geom_hline(
    yintercept = max_counts,
    linetype = "dashed"
  ) +
  NoLegend() +
  theme_classic(
    base_size = 10
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    )
  )

p_mt_threshold <- VlnPlot(
  object = scRNA,
  group.by = "sample_id",
  features = "percent.mt",
  pt.size = 0,
  raster = FALSE
) +
  geom_hline(
    yintercept = max_percent_mt,
    linetype = "dashed"
  ) +
  NoLegend() +
  theme_classic(
    base_size = 10
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    )
  )

threshold_panel <- (
  p_feature_threshold |
    p_count_threshold |
    p_mt_threshold
)

save_plot(
  plot_object = threshold_panel,
  file_stem = "QC_filtering_thresholds",
  width = 15,
  height = 5
)


# 13. Apply cell-level QC thresholds -------------------------------------------

sample_metadata <- scRNA@meta.data %>%
  transmute(
    sample_id = as.character(
      sample_id
    ),
    treatment = as.character(
      treatment
    ),
    age = as.character(
      age
    ),
    group = as.character(
      group
    ),
    batch = as.character(
      batch
    )
  ) %>%
  distinct()

duplicated_sample_metadata <- sample_metadata %>%
  count(
    sample_id,
    name = "n_metadata_rows"
  ) %>%
  filter(
    n_metadata_rows > 1
  )

if (nrow(duplicated_sample_metadata) > 0) {
  stop(
    "At least one sample maps to multiple treatment, age, group, or batch ",
    "values."
  )
}

cells_before_qc <- scRNA@meta.data %>%
  transmute(
    sample_id = as.character(
      sample_id
    )
  ) %>%
  count(
    sample_id,
    name = "cells_before_qc"
  )

scRNA <- subset(
  x = scRNA,
  subset =
    nFeature_RNA > min_features &
      nFeature_RNA < max_features &
      nCount_RNA < max_counts &
      percent.mt < max_percent_mt
)

if (ncol(scRNA) == 0) {
  stop(
    "No cells passed the specified QC thresholds."
  )
}

cells_after_qc <- scRNA@meta.data %>%
  transmute(
    sample_id = as.character(
      sample_id
    )
  ) %>%
  count(
    sample_id,
    name = "cells_after_qc"
  )


# 14. Export cell-retention and post-QC summaries ------------------------------

cell_retention <- sample_batch_information %>%
  select(
    sample_id
  ) %>%
  left_join(
    sample_metadata,
    by = "sample_id"
  ) %>%
  left_join(
    cells_before_qc,
    by = "sample_id"
  ) %>%
  left_join(
    cells_after_qc,
    by = "sample_id"
  ) %>%
  mutate(
    cells_before_qc = replace_na(
      cells_before_qc,
      0L
    ),
    cells_after_qc = replace_na(
      cells_after_qc,
      0L
    ),
    retention_percent = if_else(
      cells_before_qc > 0,
      100 * cells_after_qc / cells_before_qc,
      NA_real_
    )
  )

write.csv(
  cell_retention,
  file = file.path(
    output_table_dir,
    "QC_cell_retention_by_sample.csv"
  ),
  row.names = FALSE
)

qc_summary_post <- summarise_qc(
  object = scRNA,
  stage = "Post-QC"
)

qc_summary <- bind_rows(
  qc_summary_pre,
  qc_summary_post
)

write.csv(
  qc_summary,
  file = file.path(
    output_table_dir,
    "QC_metric_summary_by_sample.csv"
  ),
  row.names = FALSE
)

qc_plots_post <- lapply(
  qc_features,
  function(feature_name) {

    make_qc_violin_plot(
      object = scRNA,
      feature_name = feature_name,
      plot_title = paste0(
        feature_name,
        " (Post-QC)"
      )
    )
  }
)

post_qc_panel <- wrap_plots(
  qc_plots_post,
  ncol = 2
)

save_plot(
  plot_object = post_qc_panel,
  file_stem = "QC_metrics_after_filtering",
  width = 14,
  height = 10
)


# 15. Plot nCount_RNA versus nFeature_RNA --------------------------------------

p_feature_scatter <- FeatureScatter(
  object = scRNA,
  feature1 = "nCount_RNA",
  feature2 = "nFeature_RNA",
  group.by = "sample_id"
) +
  theme_classic(
    base_size = 11
  )

save_plot(
  plot_object = p_feature_scatter,
  file_stem = "QC_nCount_vs_nFeature_after_filtering",
  width = 7,
  height = 6
)


# 16. Save the filtered object and QC parameters -------------------------------

saveRDS(
  scRNA,
  file = file.path(
    output_data_dir,
    "scRNA_after_QC.rds"
  ),
  compress = "gzip"
)

qc_thresholds <- tibble(
  metric = c(
    "nFeature_RNA",
    "nFeature_RNA",
    "nCount_RNA",
    "percent.mt"
  ),
  comparison = c(
    ">",
    "<",
    "<",
    "<"
  ),
  threshold = c(
    min_features,
    max_features,
    max_counts,
    max_percent_mt
  )
)

write.csv(
  qc_thresholds,
  file = file.path(
    output_table_dir,
    "QC_filtering_thresholds.csv"
  ),
  row.names = FALSE
)

qc_parameters <- c(
  paste0(
    "Input file: ",
    input_file
  ),
  paste0(
    "Minimum detected genes per cell: > ",
    min_features
  ),
  paste0(
    "Maximum detected genes per cell: < ",
    max_features
  ),
  paste0(
    "Maximum UMI count per cell: < ",
    max_counts
  ),
  paste0(
    "Maximum mitochondrial transcript percentage: < ",
    max_percent_mt
  ),
  paste0(
    "Cells before QC: ",
    sum(
      cell_retention$cells_before_qc
    )
  ),
  paste0(
    "Cells after QC: ",
    sum(
      cell_retention$cells_after_qc
    )
  ),
  paste0(
    "Overall retention percentage: ",
    round(
      100 *
        sum(
          cell_retention$cells_after_qc
        ) /
        sum(
          cell_retention$cells_before_qc
        ),
      2
    ),
    "%"
  ),
  paste0(
    "Sequencing batches: ",
    paste(
      unique(
        sample_batch_information$batch
      ),
      collapse = ", "
    )
  ),
  paste0(
    "Mitochondrial genes detected: ",
    length(
      mitochondrial_genes
    )
  ),
  paste0(
    "Ribosomal genes detected: ",
    length(
      ribosomal_genes
    )
  ),
  paste0(
    "Haemoglobin genes detected: ",
    length(
      haemoglobin_genes_present
    )
  ),
  paste0(
    "Haemoglobin genes used: ",
    paste(
      haemoglobin_genes_present,
      collapse = ", "
    )
  ),
  paste0(
    "Ribosomal and haemoglobin transcript percentages were calculated ",
    "for QC visualization but were not used as filtering criteria."
  )
)

writeLines(
  qc_parameters,
  con = file.path(
    output_table_dir,
    "QC_filtering_parameters.txt"
  )
)

writeLines(
  capture.output(
    sessionInfo()
  ),
  con = file.path(
    output_table_dir,
    "QC_sessionInfo.txt"
  )
)

message(
  "Quality-control analysis completed successfully."
)

message(
  "Filtered Seurat object saved to: ",
  file.path(
    output_data_dir,
    "scRNA_after_QC.rds"
  )
)
