# ==============================================================================
# 03. Dimensionality reduction, batch integration, and clustering
#
# Description:
# This script loads the QC-filtered Seurat object generated by
# 02_quality_control.R, performs SCTransform normalization and principal-
# component analysis, and creates two parallel analysis branches:
#
#   1. Harmony batch integration using the metadata column "batch";
#   2. no batch correction, using the original PCA embedding.
#
# For each branch, the script generates a UMAP embedding, constructs a
# shared-nearest-neighbour graph, performs clustering across a prespecified
# resolution grid, exports clustering metadata and cell-count summaries, and
# saves the processed Seurat object.
#
# Author:
# Jinjin Zhu
#
# Input:
#   DATA/OUTPUT/scRNA_after_QC.rds
#
# Main outputs:
#   DATA/OUTPUT/scRNA_HarmonyIntegrated.rds
#   DATA/OUTPUT/scRNA_NoBatchCorrection.rds
#   TABLE/STEP3_dimension_reduction/
#   FIGURE/STEP3_dimension_reduction/
# ==============================================================================


# 1. Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(tibble)
  library(harmony)
  library(ggplot2)
  library(patchwork)
})


# 2. Define project paths -------------------------------------------------------

input_file <- "DATA/OUTPUT/scRNA_after_QC.rds"

output_data_dir <- "DATA/OUTPUT"
output_table_dir <- "TABLE/STEP3_dimension_reduction"
output_figure_dir <- "FIGURE/STEP3_dimension_reduction"

dir.create(
  output_data_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  output_table_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  output_figure_dir,
  recursive = TRUE,
  showWarnings = FALSE
)


# 3. Define analysis parameters ------------------------------------------------

random_seed <- 1234

n_pcs <- 50
dims_use <- 1:30

harmony_max_iterations <- 20

harmony_resolutions <- c(
  0.1,
  0.3,
  0.5,
  0.7,
  1.0
)

pca_resolutions <- c(
  0.1,
  0.2,
  0.3,
  0.5,
  0.7,
  1.0
)

set.seed(
  random_seed
)


# 4. Define helper functions ----------------------------------------------------

save_plot <- function(
  plot_object,
  file_stem,
  width,
  height
) {

  ggsave(
    filename = file.path(
      output_figure_dir,
      paste0(
        file_stem,
        ".pdf"
      )
    ),
    plot = plot_object,
    width = width,
    height = height,
    units = "in"
  )

  ggsave(
    filename = file.path(
      output_figure_dir,
      paste0(
        file_stem,
        ".tiff"
      )
    ),
    plot = plot_object,
    width = width,
    height = height,
    units = "in",
    dpi = 600,
    compression = "lzw"
  )
}


validate_reduction <- function(
  object,
  reduction_name,
  object_name
) {

  if (!reduction_name %in% Reductions(object)) {
    stop(
      "Reduction '",
      reduction_name,
      "' was not generated for ",
      object_name,
      "."
    )
  }

  invisible(TRUE)
}


extract_cluster_columns <- function(
  object
) {

  grep(
    pattern = "_snn_res\\.",
    x = colnames(
      object@meta.data
    ),
    value = TRUE
  )
}


export_cluster_assignments <- function(
  object,
  branch_name,
  output_file
) {

  cluster_columns <- extract_cluster_columns(
    object
  )

  if (length(cluster_columns) == 0) {
    stop(
      "No clustering columns were found for branch: ",
      branch_name
    )
  }

  available_metadata <- intersect(
    c(
      "sample_id",
      "orig.ident",
      "treatment",
      "age",
      "group",
      "batch"
    ),
    colnames(
      object@meta.data
    )
  )

  cluster_table <- object@meta.data %>%
    rownames_to_column(
      "cell_barcode"
    ) %>%
    select(
      cell_barcode,
      all_of(
        available_metadata
      ),
      all_of(
        cluster_columns
      )
    )

  write.csv(
    cluster_table,
    file = output_file,
    row.names = FALSE
  )

  return(
    cluster_columns
  )
}


summarise_cluster_sizes <- function(
  object,
  branch_name,
  cluster_columns
) {

  bind_rows(
    lapply(
      cluster_columns,
      function(cluster_column) {

        object@meta.data %>%
          transmute(
            sample_id = as.character(
              sample_id
            ),
            group = as.character(
              group
            ),
            cluster = as.character(
              .data[
                [cluster_column]
              ]
            )
          ) %>%
          count(
            sample_id,
            group,
            cluster,
            name = "n_cells"
          ) %>%
          mutate(
            branch = branch_name,
            clustering_column = cluster_column,
            .before = 1
          )
      }
    )
  )
}


make_diagnostic_umap <- function(
  object,
  group_column,
  plot_title
) {

  DimPlot(
    object = object,
    reduction = "umap",
    group.by = group_column,
    pt.size = 0.1,
    raster = TRUE
  ) +
    ggtitle(
      plot_title
    ) +
    theme_classic(
      base_size = 11
    ) +
    theme(
      axis.title = element_blank(),
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      plot.title = element_text(
        hjust = 0.5
      )
    )
}


# 5. Load and validate the QC-filtered Seurat object ---------------------------

if (!file.exists(input_file)) {
  stop(
    "Input file does not exist: ",
    input_file
  )
}

scRNA_qc <- readRDS(
  input_file
)

if (!inherits(scRNA_qc, "Seurat")) {
  stop(
    "The input file must contain a Seurat object."
  )
}

if (!"RNA" %in% Assays(scRNA_qc)) {
  stop(
    "The Seurat object does not contain an RNA assay."
  )
}

required_metadata <- c(
  "sample_id",
  "treatment",
  "age",
  "group",
  "batch"
)

missing_metadata <- setdiff(
  required_metadata,
  colnames(
    scRNA_qc@meta.data
  )
)

if (length(missing_metadata) > 0) {
  stop(
    "The following required metadata columns are missing: ",
    paste(
      missing_metadata,
      collapse = ", "
    )
  )
}

if (anyNA(scRNA_qc$batch) ||
    any(as.character(scRNA_qc$batch) == "")) {
  stop(
    "Missing values were detected in the batch metadata."
  )
}

if (n_distinct(
  as.character(
    scRNA_qc$batch
  )
) < 2) {
  stop(
    "Harmony integration requires at least two batch levels."
  )
}

if (anyNA(scRNA_qc$group) ||
    any(as.character(scRNA_qc$group) == "")) {
  stop(
    "Missing values were detected in the group metadata."
  )
}

sample_metadata_check <- scRNA_qc@meta.data %>%
  transmute(
    sample_id = as.character(
      sample_id
    ),
    treatment = as.character(
      treatment
    ),
    age = as.character(
      age
    ),
    group = as.character(
      group
    ),
    batch = as.character(
      batch
    )
  ) %>%
  distinct()

duplicated_sample_metadata <- sample_metadata_check %>%
  count(
    sample_id,
    name = "n_metadata_rows"
  ) %>%
  filter(
    n_metadata_rows > 1
  )

if (nrow(duplicated_sample_metadata) > 0) {
  stop(
    "At least one sample ID maps to multiple treatment, age, group, ",
    "or batch values."
  )
}

input_summary <- tibble(
  input_file = input_file,
  n_cells = ncol(
    scRNA_qc
  ),
  n_features = nrow(
    scRNA_qc
  ),
  n_samples = n_distinct(
    scRNA_qc$sample_id
  ),
  n_groups = n_distinct(
    scRNA_qc$group
  ),
  n_batches = n_distinct(
    scRNA_qc$batch
  )
)

write.csv(
  input_summary,
  file = file.path(
    output_table_dir,
    "input_object_summary.csv"
  ),
  row.names = FALSE
)

write.csv(
  sample_metadata_check,
  file = file.path(
    output_table_dir,
    "sample_metadata_used_for_integration.csv"
  ),
  row.names = FALSE
)


# 6. Perform SCTransform normalization -----------------------------------------

# SCTransform is performed once. The normalized object and PCA embedding are
# then copied into the Harmony and no-correction branches so that both branches
# begin from the same normalized expression matrix.

scRNA_sct <- SCTransform(
  object = scRNA_qc,
  assay = "RNA",
  new.assay.name = "SCT",
  verbose = FALSE
)

DefaultAssay(
  scRNA_sct
) <- "SCT"

if (!"SCT" %in% Assays(scRNA_sct)) {
  stop(
    "SCTransform did not generate an SCT assay."
  )
}


# 7. Perform principal-component analysis -------------------------------------

scRNA_sct <- RunPCA(
  object = scRNA_sct,
  assay = "SCT",
  npcs = n_pcs,
  verbose = FALSE,
  seed.use = random_seed
)

validate_reduction(
  object = scRNA_sct,
  reduction_name = "pca",
  object_name = "SCTransform-normalized object"
)

available_pcs <- ncol(
  Embeddings(
    object = scRNA_sct,
    reduction = "pca"
  )
)

if (max(dims_use) > available_pcs) {
  stop(
    "dims_use requests PC ",
    max(dims_use),
    ", but only ",
    available_pcs,
    " principal components are available."
  )
}

p_elbow <- ElbowPlot(
  object = scRNA_sct,
  ndims = n_pcs
) +
  ggtitle(
    "PCA elbow plot"
  ) +
  theme_classic(
    base_size = 11
  )

save_plot(
  plot_object = p_elbow,
  file_stem = "PCA_elbow_plot",
  width = 5,
  height = 4
)


# ==============================================================================
# Branch A: Harmony batch integration
# ==============================================================================


# 8. Create the Harmony branch -------------------------------------------------

scRNA_harmony <- scRNA_sct


# 9. Run Harmony integration ---------------------------------------------------

scRNA_harmony <- RunHarmony(
  object = scRNA_harmony,
  group.by.vars = "batch",
  reduction = "pca",
  assay.use = "SCT",
  max.iter.harmony = harmony_max_iterations,
  reduction.save = "harmony",
  plot_convergence = FALSE,
  verbose = TRUE
)

validate_reduction(
  object = scRNA_harmony,
  reduction_name = "harmony",
  object_name = "Harmony branch"
)


# 10. Generate the Harmony-based UMAP ------------------------------------------

scRNA_harmony <- RunUMAP(
  object = scRNA_harmony,
  reduction = "harmony",
  dims = dims_use,
  seed.use = random_seed,
  reduction.name = "umap",
  reduction.key = "UMAP_",
  verbose = FALSE
)

validate_reduction(
  object = scRNA_harmony,
  reduction_name = "umap",
  object_name = "Harmony branch"
)


# 11. Construct the Harmony-based neighbour graph ------------------------------

scRNA_harmony <- FindNeighbors(
  object = scRNA_harmony,
  reduction = "harmony",
  dims = dims_use,
  verbose = FALSE
)


# 12. Cluster the Harmony branch ------------------------------------------------

for (resolution_value in harmony_resolutions) {

  scRNA_harmony <- FindClusters(
    object = scRNA_harmony,
    resolution = resolution_value,
    random.seed = random_seed,
    verbose = FALSE
  )
}

harmony_cluster_columns <- extract_cluster_columns(
  scRNA_harmony
)

expected_harmony_columns <- paste0(
  "SCT_snn_res.",
  harmony_resolutions
)

missing_harmony_columns <- setdiff(
  expected_harmony_columns,
  harmony_cluster_columns
)

if (length(missing_harmony_columns) > 0) {
  warning(
    "The following expected Harmony clustering columns were not detected: ",
    paste(
      missing_harmony_columns,
      collapse = ", "
    )
  )
}


# 13. Generate Harmony diagnostic UMAPs ----------------------------------------

p_harmony_batch <- make_diagnostic_umap(
  object = scRNA_harmony,
  group_column = "batch",
  plot_title = "Harmony-integrated UMAP by batch"
)

p_harmony_group <- make_diagnostic_umap(
  object = scRNA_harmony,
  group_column = "group",
  plot_title = "Harmony-integrated UMAP by group"
)

p_harmony_sample <- make_diagnostic_umap(
  object = scRNA_harmony,
  group_column = "sample_id",
  plot_title = "Harmony-integrated UMAP by sample"
)

harmony_diagnostic_panel <- (
  p_harmony_batch |
    p_harmony_group |
    p_harmony_sample
)

save_plot(
  plot_object = harmony_diagnostic_panel,
  file_stem = "Harmony_UMAP_diagnostics",
  width = 15,
  height = 4.5
)


# 14. Export and save the Harmony branch ---------------------------------------

harmony_cluster_columns <- export_cluster_assignments(
  object = scRNA_harmony,
  branch_name = "Harmony",
  output_file = file.path(
    output_table_dir,
    "Harmony_cluster_assignments.csv"
  )
)

harmony_cluster_sizes <- summarise_cluster_sizes(
  object = scRNA_harmony,
  branch_name = "Harmony",
  cluster_columns = harmony_cluster_columns
)

write.csv(
  harmony_cluster_sizes,
  file = file.path(
    output_table_dir,
    "Harmony_cluster_sizes_by_sample.csv"
  ),
  row.names = FALSE
)

saveRDS(
  scRNA_harmony,
  file = file.path(
    output_data_dir,
    "scRNA_HarmonyIntegrated.rds"
  ),
  compress = "gzip"
)


# ==============================================================================
# Branch B: no batch correction
# ==============================================================================


# 15. Create the no-correction branch ------------------------------------------

scRNA_no_batch <- scRNA_sct


# 16. Generate the PCA-based UMAP ----------------------------------------------

scRNA_no_batch <- RunUMAP(
  object = scRNA_no_batch,
  reduction = "pca",
  dims = dims_use,
  seed.use = random_seed,
  reduction.name = "umap",
  reduction.key = "UMAP_",
  verbose = FALSE
)

validate_reduction(
  object = scRNA_no_batch,
  reduction_name = "umap",
  object_name = "No-correction branch"
)


# 17. Construct the PCA-based neighbour graph ----------------------------------

scRNA_no_batch <- FindNeighbors(
  object = scRNA_no_batch,
  reduction = "pca",
  dims = dims_use,
  verbose = FALSE
)


# 18. Cluster the no-correction branch -----------------------------------------

for (resolution_value in pca_resolutions) {

  scRNA_no_batch <- FindClusters(
    object = scRNA_no_batch,
    resolution = resolution_value,
    random.seed = random_seed,
    verbose = FALSE
  )
}

pca_cluster_columns <- extract_cluster_columns(
  scRNA_no_batch
)

expected_pca_columns <- paste0(
  "SCT_snn_res.",
  pca_resolutions
)

missing_pca_columns <- setdiff(
  expected_pca_columns,
  pca_cluster_columns
)

if (length(missing_pca_columns) > 0) {
  warning(
    "The following expected no-correction clustering columns were not detected: ",
    paste(
      missing_pca_columns,
      collapse = ", "
    )
  )
}


# 19. Generate no-correction diagnostic UMAPs ----------------------------------

p_no_batch_batch <- make_diagnostic_umap(
  object = scRNA_no_batch,
  group_column = "batch",
  plot_title = "Uncorrected UMAP by batch"
)

p_no_batch_group <- make_diagnostic_umap(
  object = scRNA_no_batch,
  group_column = "group",
  plot_title = "Uncorrected UMAP by group"
)

p_no_batch_sample <- make_diagnostic_umap(
  object = scRNA_no_batch,
  group_column = "sample_id",
  plot_title = "Uncorrected UMAP by sample"
)

no_batch_diagnostic_panel <- (
  p_no_batch_batch |
    p_no_batch_group |
    p_no_batch_sample
)

save_plot(
  plot_object = no_batch_diagnostic_panel,
  file_stem = "No_batch_correction_UMAP_diagnostics",
  width = 15,
  height = 4.5
)


# 20. Export and save the no-correction branch ---------------------------------

pca_cluster_columns <- export_cluster_assignments(
  object = scRNA_no_batch,
  branch_name = "No batch correction",
  output_file = file.path(
    output_table_dir,
    "No_batch_correction_cluster_assignments.csv"
  )
)

pca_cluster_sizes <- summarise_cluster_sizes(
  object = scRNA_no_batch,
  branch_name = "No batch correction",
  cluster_columns = pca_cluster_columns
)

write.csv(
  pca_cluster_sizes,
  file = file.path(
    output_table_dir,
    "No_batch_correction_cluster_sizes_by_sample.csv"
  ),
  row.names = FALSE
)

saveRDS(
  scRNA_no_batch,
  file = file.path(
    output_data_dir,
    "scRNA_NoBatchCorrection.rds"
  ),
  compress = "gzip"
)


# 21. Export a direct comparison of the two branches ---------------------------

p_branch_harmony <- DimPlot(
  object = scRNA_harmony,
  reduction = "umap",
  group.by = "group",
  pt.size = 0.1,
  raster = TRUE
) +
  ggtitle(
    "Harmony integration"
  ) +
  theme_classic(
    base_size = 11
  ) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    plot.title = element_text(
      hjust = 0.5
    )
  )

p_branch_no_batch <- DimPlot(
  object = scRNA_no_batch,
  reduction = "umap",
  group.by = "group",
  pt.size = 0.1,
  raster = TRUE
) +
  ggtitle(
    "No batch correction"
  ) +
  theme_classic(
    base_size = 11
  ) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    plot.title = element_text(
      hjust = 0.5
    )
  )

branch_comparison_plot <- (
  p_branch_harmony |
    p_branch_no_batch
)

save_plot(
  plot_object = branch_comparison_plot,
  file_stem = "Harmony_vs_no_batch_correction",
  width = 10,
  height = 4.5
)


# 22. Save analysis parameters -------------------------------------------------

analysis_parameters <- tibble(
  parameter = c(
    "Input file",
    "Normalization assay",
    "Normalization method",
    "Number of principal components",
    "Dimensions used",
    "Harmony integration variable",
    "Harmony maximum iterations",
    "Harmony clustering resolutions",
    "No-correction clustering resolutions",
    "Random seed"
  ),
  value = c(
    input_file,
    "RNA",
    "SCTransform",
    as.character(
      n_pcs
    ),
    paste0(
      min(dims_use),
      "-",
      max(dims_use)
    ),
    "batch",
    as.character(
      harmony_max_iterations
    ),
    paste(
      harmony_resolutions,
      collapse = ", "
    ),
    paste(
      pca_resolutions,
      collapse = ", "
    ),
    as.character(
      random_seed
    )
  )
)

write.csv(
  analysis_parameters,
  file = file.path(
    output_table_dir,
    "dimension_reduction_clustering_parameters.csv"
  ),
  row.names = FALSE
)

writeLines(
  paste0(
    analysis_parameters$parameter,
    ": ",
    analysis_parameters$value
  ),
  con = file.path(
    output_table_dir,
    "dimension_reduction_clustering_parameters.txt"
  )
)


# 23. Save software information ------------------------------------------------

writeLines(
  capture.output(
    sessionInfo()
  ),
  con = file.path(
    output_table_dir,
    "dimension_reduction_clustering_sessionInfo.txt"
  )
)

message(
  "Dimensionality reduction, Harmony integration, and clustering completed ",
  "successfully."
)

message(
  "Harmony-integrated object saved to: ",
  file.path(
    output_data_dir,
    "scRNA_HarmonyIntegrated.rds"
  )
)

message(
  "No-correction object saved to: ",
  file.path(
    output_data_dir,
    "scRNA_NoBatchCorrection.rds"
  )
)
