# ==============================================================================
# 08d. Optional ClusterGVis pseudotime heatmap
#
# Description:
# This optional script reproduces the ClusterGVis-based visualization workflow.
# ClusterGVis performs a separate k-means clustering of the smoothed pseudotime
# expression matrix. These clusters are not the same as the gene modules
# generated by monocle3::find_gene_modules().
#
# Configuration:
#   config/monocle3/08d_ClusterGVis_manifest.csv
# ==============================================================================

suppressPackageStartupMessages({
  library(monocle3)
  library(ClusterGVis)
  library(dplyr)
  library(tibble)
  library(readxl)
  library(stringr)
  library(grid)
})

manifest_file <- "config/monocle3/08d_ClusterGVis_manifest.csv"

output_table_root <- "TABLE/Monocle3"
output_figure_root <- "FIGURE/Monocle3"

dir.create(output_table_root, recursive = TRUE, showWarnings = FALSE)
dir.create(output_figure_root, recursive = TRUE, showWarnings = FALSE)


sanitize_name <- function(x) {
  x <- gsub("[^A-Za-z0-9._-]+", "_", as.character(x))
  gsub("_+", "_", x)
}


read_gene_list <- function(file) {
  if (is.na(file) || trimws(file) == "" || !file.exists(file)) {
    return(character(0))
  }

  table <- read.csv(
    file,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )

  if (!"gene" %in% colnames(table)) {
    stop("Marked-gene file must contain a gene column.")
  }

  genes <- unique(trimws(as.character(table$gene)))
  genes[!is.na(genes) & genes != ""]
}


read_term_table <- function(file) {
  if (is.na(file) || trimws(file) == "" || !file.exists(file)) {
    return(NULL)
  }

  table <- read.csv(
    file,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )

  required <- c("id", "term", "pval")
  missing <- setdiff(required, colnames(table))

  if (length(missing) > 0) {
    stop(
      "GO-term table is missing columns: ",
      paste(missing, collapse = ", ")
    )
  }

  table
}


run_one_clustergvis <- function(row) {
  analysis_id <- row$analysis_id[[1]]
  analysis_id_safe <- sanitize_name(analysis_id)

  table_dir <- file.path(output_table_root, analysis_id_safe)
  figure_dir <- file.path(output_figure_root, analysis_id_safe)

  dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
  dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

  cds <- readRDS(row$cds_file[[1]])

  if (!inherits(cds, "cell_data_set")) {
    stop("CDS file does not contain a Monocle 3 cell_data_set.")
  }

  module_table <- read.csv(
    row$module_file[[1]],
    stringsAsFactors = FALSE,
    check.names = FALSE
  )

  if (!"id" %in% colnames(module_table)) {
    stop("Module file must contain an id column.")
  }

  pseudotime_gene_ids <- unique(as.character(module_table$id))
  pseudotime_gene_ids <- intersect(pseudotime_gene_ids, rownames(cds))

  if (length(pseudotime_gene_ids) == 0) {
    stop("No module genes were found in the CDS.")
  }

  smoothed_matrix <- ClusterGVis::pre_pseudotime_matrix(
    cds_obj = cds,
    gene_list = pseudotime_gene_ids
  )

  set.seed(row$cluster_seed[[1]])

  clustered_data <- ClusterGVis::clusterData(
    exp = smoothed_matrix,
    cluster.method = "kmeans",
    cluster.num = row$cluster_number[[1]],
    seed = row$cluster_seed[[1]]
  )

  cluster_assignments <- clustered_data$long.res |>
    filter(cell_type == 1) |>
    select(cluster, gene, cluster_name) |>
    distinct()

  if ("module" %in% colnames(module_table)) {
    cluster_assignments$monocle_module <- module_table$module[
      match(cluster_assignments$gene, module_table$id)
    ]
  }

  write.csv(
    cluster_assignments,
    file = file.path(table_dir, "ClusterGVis_gene_clusters.csv"),
    row.names = FALSE
  )

  marked_genes <- read_gene_list(row$marked_gene_file[[1]])
  term_table <- read_term_table(row$term_file[[1]])

  cluster_order <- trimws(
    unlist(
      strsplit(
        as.character(row$cluster_order[[1]]),
        ";",
        fixed = TRUE
      )
    )
  )

  cluster_order <- cluster_order[cluster_order != ""]

  pdf(
    file.path(figure_dir, "ClusterGVis_pseudotime_heatmap.pdf"),
    width = row$plot_width[[1]],
    height = row$plot_height[[1]],
    useDingbats = FALSE
  )

  ClusterGVis::visCluster(
    object = clustered_data,
    border = TRUE,
    show_row_names = FALSE,
    row_names_gp = gpar(fontsize = 3),
    plot.type = "both",
    line.size = 0.2,
    line.col = "grey90",
    line.side = "left",
    add.sampleanno = FALSE,
    cluster.order = if (length(cluster_order) > 0) cluster_order else NULL,
    markGenes = if (length(marked_genes) > 0) marked_genes else NULL,
    markGenes.side = "left",
    genes.gp = c("italic", 10, NA),
    annoTerm.data = term_table,
    annoTerm.mside = "right",
    go.col = "black",
    go.size = 12,
    term.text.limit = c(10, 18),
    add.bar = FALSE,
    bar.width = 8
  )

  dev.off()

  tibble(
    analysis_id = analysis_id,
    status = "completed",
    n_input_genes = length(pseudotime_gene_ids),
    n_kmeans_clusters = row$cluster_number[[1]]
  )
}


if (!file.exists(manifest_file)) {
  stop("ClusterGVis manifest does not exist: ", manifest_file)
}

manifest <- read.csv(
  manifest_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
) |>
  mutate(
    across(
      c(
        analysis_id,
        cds_file,
        module_file,
        marked_gene_file,
        term_file,
        cluster_order
      ),
      ~ trimws(as.character(.x))
    ),
    cluster_number = as.integer(cluster_number),
    cluster_seed = as.integer(cluster_seed),
    plot_width = as.numeric(plot_width),
    plot_height = as.numeric(plot_height)
  )

results <- vector("list", nrow(manifest))

for (i in seq_len(nrow(manifest))) {
  current_id <- manifest$analysis_id[[i]]

  results[[i]] <- tryCatch(
    run_one_clustergvis(manifest[i, , drop = FALSE]),
    error = function(e) {
      message(
        "ClusterGVis analysis failed: ",
        current_id,
        "\nReason: ",
        conditionMessage(e)
      )

      tibble(
        analysis_id = current_id,
        status = "failed",
        n_input_genes = NA_integer_,
        n_kmeans_clusters = NA_integer_,
        error_message = conditionMessage(e)
      )
    }
  )
}

summary_table <- bind_rows(results)

write.csv(
  summary_table,
  file = file.path(output_table_root, "08d_ClusterGVis_summary.csv"),
  row.names = FALSE
)

writeLines(
  capture.output(sessionInfo()),
  con = file.path(output_table_root, "08d_ClusterGVis_sessionInfo.txt")
)

print(summary_table)
