# ==============================================================================
# 09. scFEA flux post-processing and visualization across multiple analyses
#
# Description:
# This script imports per-cell metabolic-flux matrices generated by scFEA and
# processes one or more analyses defined in an external manifest. For each
# analysis, it:
#
#   1. matches scFEA cell barcodes to Seurat metadata;
#   2. calculates mean flux for each configured cell state;
#   3. optionally calculates biological-sample-level mean flux;
#   4. removes modules with zero or undefined variance across cell states;
#   5. applies reviewed cell-state and metabolic-module orders;
#   6. exports full and selected-module flux matrices;
#   7. generates full and selected-module heatmaps;
#   8. saves a compact RDS bundle and analysis parameters.
#
# Important:
# This script does not run the scFEA model. The exact scFEA command, model
# version, input expression matrix, and model files used to generate the flux
# matrix should be archived separately.
#
# Statistical note:
# Cell-state means are used for descriptive heatmaps. They must not be treated
# as independent biological replicates for inferential statistics. When a valid
# biological-sample column is supplied, sample-level summaries are also exported.
#
# Author:
# Jinjin Zhu
#
# Configuration:
#   config/scFEA/09_scFEA_manifest.csv
#
# Main outputs:
#   DATA/OUTPUT/scFEA/
#   TABLE/scFEA/<analysis_id>/
#   FIGURE/scFEA/<analysis_id>/
# ==============================================================================


# 1. Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(tibble)
  library(readxl)
  library(ComplexHeatmap)
  library(circlize)
  library(grid)
})


# 2. Define project paths -------------------------------------------------------

manifest_file <- "config/scFEA/09_scFEA_manifest.csv"

output_data_root <- "DATA/OUTPUT/scFEA"
output_table_root <- "TABLE/scFEA"
output_figure_root <- "FIGURE/scFEA"

dir.create(
  output_data_root,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  output_table_root,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  output_figure_root,
  recursive = TRUE,
  showWarnings = FALSE
)


# 3. Define global plotting parameters -----------------------------------------

heatmap_color_function <- circlize::colorRamp2(
  c(
    -2,
    -1,
    0,
    1,
    2
  ),
  c(
    "#2166AC",
    "#90C0DC",
    "white",
    "#EF8C65",
    "#B2182B"
  )
)


# 4. Define helper functions ----------------------------------------------------

as_flag <- function(x) {

  tolower(
    trimws(
      as.character(
        x
      )
    )
  ) %in% c(
    "true",
    "t",
    "1",
    "yes",
    "y"
  )
}


sanitize_name <- function(x) {

  x <- gsub(
    pattern = "[^A-Za-z0-9._-]+",
    replacement = "_",
    x = as.character(
      x
    )
  )

  gsub(
    pattern = "_+",
    replacement = "_",
    x = x
  )
}


read_external_table <- function(
  file,
  required = TRUE
) {

  file <- trimws(
    as.character(
      file
    )
  )

  if (is.na(
    file
  ) ||
      file == "") {

    if (required) {
      stop(
        "A required file path is empty."
      )
    }

    return(
      NULL
    )
  }

  if (!file.exists(
    file
  )) {

    if (required) {
      stop(
        "Input file does not exist: ",
        file
      )
    }

    return(
      NULL
    )
  }

  extension <- tolower(
    tools::file_ext(
      file
    )
  )

  if (extension == "csv") {

    table <- read.csv(
      file,
      stringsAsFactors = FALSE,
      check.names = FALSE
    )

  } else if (extension %in% c(
    "tsv",
    "txt"
  )) {

    table <- read.delim(
      file,
      stringsAsFactors = FALSE,
      check.names = FALSE
    )

  } else if (extension %in% c(
    "xlsx",
    "xls"
  )) {

    table <- readxl::read_excel(
      file,
      sheet = 1
    ) %>%
      as.data.frame(
        stringsAsFactors = FALSE
      )

  } else {

    stop(
      "Unsupported table format: ",
      file
    )
  }

  table
}


validate_manifest <- function(manifest) {

  required_columns <- c(
    "analysis_id",
    "flux_file",
    "barcode_column",
    "module_info_file",
    "seurat_file",
    "celltype_column",
    "sample_column",
    "state_annotation_file",
    "module_order_file",
    "selected_module_file",
    "scfea_command_file",
    "save_per_cell_flux",
    "full_heatmap_width",
    "full_heatmap_height",
    "selected_heatmap_width",
    "selected_heatmap_height"
  )

  missing_columns <- setdiff(
    required_columns,
    colnames(
      manifest
    )
  )

  if (length(
    missing_columns
  ) > 0) {

    stop(
      "The scFEA manifest is missing columns: ",
      paste(
        missing_columns,
        collapse = ", "
      )
    )
  }

  manifest <- manifest %>%
    mutate(
      across(
        c(
          analysis_id,
          flux_file,
          barcode_column,
          module_info_file,
          seurat_file,
          celltype_column,
          sample_column,
          state_annotation_file,
          module_order_file,
          selected_module_file,
          scfea_command_file
        ),
        ~ trimws(
          as.character(
            .x
          )
        )
      ),
      save_per_cell_flux = as_flag(
        save_per_cell_flux
      ),
      full_heatmap_width = as.numeric(
        full_heatmap_width
      ),
      full_heatmap_height = as.numeric(
        full_heatmap_height
      ),
      selected_heatmap_width = as.numeric(
        selected_heatmap_width
      ),
      selected_heatmap_height = as.numeric(
        selected_heatmap_height
      )
    )

  if (any(
    is.na(
      manifest$analysis_id
    ) |
      manifest$analysis_id == ""
  )) {

    stop(
      "Every manifest row must contain a non-empty analysis_id."
    )
  }

  if (anyDuplicated(
    manifest$analysis_id
  )) {

    duplicated_ids <- unique(
      manifest$analysis_id[
        duplicated(
          manifest$analysis_id
        )
      ]
    )

    stop(
      "Duplicated analysis_id values were detected: ",
      paste(
        duplicated_ids,
        collapse = ", "
      )
    )
  }

  manifest
}


read_flux_matrix <- function(
  flux_file,
  barcode_column
) {

  flux_raw <- read_external_table(
    file = flux_file,
    required = TRUE
  )

  if (ncol(
    flux_raw
  ) < 2) {

    stop(
      "The flux file must contain one barcode column and at least one ",
      "metabolic-module column."
    )
  }

  if (!barcode_column %in% colnames(
    flux_raw
  )) {

    stop(
      "Barcode column '",
      barcode_column,
      "' was not found in the flux file."
    )
  }

  barcodes <- trimws(
    as.character(
      flux_raw[
        [barcode_column]
      ]
    )
  )

  if (any(
    is.na(
      barcodes
    ) |
      barcodes == ""
  )) {

    stop(
      "Missing or empty cell barcodes were detected in the flux file."
    )
  }

  if (anyDuplicated(
    barcodes
  )) {

    duplicated_barcodes <- unique(
      barcodes[
        duplicated(
          barcodes
        )
      ]
    )

    stop(
      "Duplicated cell barcodes were detected in the flux file. Examples: ",
      paste(
        head(
          duplicated_barcodes,
          10
        ),
        collapse = ", "
      )
    )
  }

  flux_table <- flux_raw[
    ,
    setdiff(
      colnames(
        flux_raw
      ),
      barcode_column
    ),
    drop = FALSE
  ]

  flux_table <- as.data.frame(
    lapply(
      flux_table,
      function(x) {

        suppressWarnings(
          as.numeric(
            as.character(
              x
            )
          )
        )
      }
    ),
    row.names = barcodes,
    check.names = FALSE
  )

  all_na_modules <- colnames(
    flux_table
  )[
    vapply(
      flux_table,
      function(x) {
        all(
          is.na(
            x
          )
        )
      },
      logical(
        1
      )
    )
  ]

  if (length(
    all_na_modules
  ) > 0) {

    stop(
      "The following flux columns could not be converted to numeric values: ",
      paste(
        all_na_modules,
        collapse = ", "
      )
    )
  }

  if (anyNA(
    flux_table
  )) {

    warning(
      "Some missing values were detected after converting the flux matrix ",
      "to numeric values."
    )
  }

  as.matrix(
    flux_table
  )
}


read_module_information <- function(
  file
) {

  module_info <- read_external_table(
    file = file,
    required = TRUE
  )

  required_columns <- c(
    "M_id",
    "M_name",
    "SM_anno"
  )

  missing_columns <- setdiff(
    required_columns,
    colnames(
      module_info
    )
  )

  if (length(
    missing_columns
  ) > 0) {

    stop(
      "The module-information file is missing columns: ",
      paste(
        missing_columns,
        collapse = ", "
      )
    )
  }

  module_info <- module_info %>%
    transmute(
      M_id = trimws(
        as.character(
          M_id
        )
      ),
      M_name = trimws(
        as.character(
          M_name
        )
      ),
      SM_anno = trimws(
        as.character(
          SM_anno
        )
      )
    )

  if (anyDuplicated(
    module_info$M_id
  )) {

    stop(
      "Duplicated M_id values were detected in the module-information file."
    )
  }

  module_info
}


read_state_annotations <- function(
  file
) {

  state_table <- read_external_table(
    file = file,
    required = TRUE
  )

  required_columns <- c(
    "celltype",
    "broad_celltype",
    "state_color",
    "broad_color",
    "order"
  )

  missing_columns <- setdiff(
    required_columns,
    colnames(
      state_table
    )
  )

  if (length(
    missing_columns
  ) > 0) {

    stop(
      "The state-annotation file is missing columns: ",
      paste(
        missing_columns,
        collapse = ", "
      )
    )
  }

  state_table <- state_table %>%
    transmute(
      celltype = trimws(
        as.character(
          celltype
        )
      ),
      broad_celltype = trimws(
        as.character(
          broad_celltype
        )
      ),
      state_color = trimws(
        as.character(
          state_color
        )
      ),
      broad_color = trimws(
        as.character(
          broad_color
        )
      ),
      order = as.numeric(
        order
      )
    ) %>%
    arrange(
      order
    )

  if (anyDuplicated(
    state_table$celltype
  )) {

    stop(
      "Duplicated celltype values were detected in the state-annotation file."
    )
  }

  broad_color_check <- state_table %>%
    distinct(
      broad_celltype,
      broad_color
    ) %>%
    count(
      broad_celltype,
      name = "n_colors"
    ) %>%
    filter(
      n_colors > 1
    )

  if (nrow(
    broad_color_check
  ) > 0) {

    stop(
      "At least one broad_celltype is assigned more than one broad_color."
    )
  }

  state_table
}


apply_module_order <- function(
  flux_matrix,
  module_info,
  module_order_file
) {

  module_order_table <- read_external_table(
    file = module_order_file,
    required = FALSE
  )

  if (is.null(
    module_order_table
  )) {

    requested_order <- module_info$M_id[
      module_info$M_id %in% rownames(
        flux_matrix
      )
    ]

  } else {

    required_columns <- c(
      "M_id",
      "order"
    )

    missing_columns <- setdiff(
      required_columns,
      colnames(
        module_order_table
      )
    )

    if (length(
      missing_columns
    ) > 0) {

      stop(
        "The module-order file is missing columns: ",
        paste(
          missing_columns,
          collapse = ", "
        )
      )
    }

    module_order_table <- module_order_table %>%
      transmute(
        M_id = trimws(
          as.character(
            M_id
          )
        ),
        order = as.numeric(
          order
        )
      ) %>%
      arrange(
        order
      )

    if (anyDuplicated(
      module_order_table$M_id
    )) {

      stop(
        "Duplicated M_id values were detected in the module-order file."
      )
    }

    missing_ordered_modules <- setdiff(
      rownames(
        flux_matrix
      ),
      module_order_table$M_id
    )

    extra_ordered_modules <- setdiff(
      module_order_table$M_id,
      rownames(
        flux_matrix
      )
    )

    if (length(
      missing_ordered_modules
    ) > 0) {

      stop(
        "The module-order file does not include retained module(s): ",
        paste(
          missing_ordered_modules,
          collapse = ", "
        )
      )
    }

    if (length(
      extra_ordered_modules
    ) > 0) {

      warning(
        "The module-order file contains module(s) absent from the processed ",
        "flux matrix: ",
        paste(
          extra_ordered_modules,
          collapse = ", "
        )
      )
    }

    requested_order <- module_order_table$M_id[
      module_order_table$M_id %in% rownames(
        flux_matrix
      )
    ]
  }

  flux_matrix[
    requested_order,
    ,
    drop = FALSE
  ]
}


row_z_score <- function(
  matrix
) {

  scaled <- t(
    scale(
      t(
        matrix
      )
    )
  )

  scaled[
    !is.finite(
      scaled
    )
  ] <- 0

  scaled
}


make_unique_module_labels <- function(
  module_information
) {

  base_labels <- ifelse(
    is.na(
      module_information$M_name
    ) |
      module_information$M_name == "",
    module_information$M_id,
    module_information$M_name
  )

  make.unique(
    base_labels,
    sep = " | "
  )
}


save_complex_heatmap <- function(
  heatmap_object,
  output_dir,
  file_stem,
  width,
  height
) {

  pdf(
    file = file.path(
      output_dir,
      paste0(
        file_stem,
        ".pdf"
      )
    ),
    width = width,
    height = height,
    useDingbats = FALSE
  )

  ComplexHeatmap::draw(
    heatmap_object,
    merge_legends = TRUE
  )

  dev.off()

  tiff(
    filename = file.path(
      output_dir,
      paste0(
        file_stem,
        ".tiff"
      )
    ),
    width = width,
    height = height,
    units = "in",
    res = 600,
    compression = "lzw"
  )

  ComplexHeatmap::draw(
    heatmap_object,
    merge_legends = TRUE
  )

  dev.off()
}


build_flux_heatmap <- function(
  scaled_flux_matrix,
  module_information,
  state_table,
  row_group_column,
  show_row_names,
  row_font_size
) {

  state_order <- state_table$celltype

  broad_levels <- unique(
    state_table$broad_celltype
  )

  state_annotation <- data.frame(
    subcelltype = factor(
      state_table$celltype,
      levels = state_order
    ),
    celltype = factor(
      state_table$broad_celltype,
      levels = broad_levels
    ),
    row.names = state_order,
    check.names = FALSE
  )

  state_colors <- setNames(
    state_table$state_color,
    state_table$celltype
  )

  broad_colors <- state_table %>%
    distinct(
      broad_celltype,
      broad_color
    )

  broad_colors <- setNames(
    broad_colors$broad_color,
    broad_colors$broad_celltype
  )

  top_annotation <- ComplexHeatmap::HeatmapAnnotation(
    df = state_annotation,
    col = list(
      subcelltype = state_colors,
      celltype = broad_colors
    ),
    show_annotation_name = FALSE
  )

  row_groups <- factor(
    as.character(
      module_information[
        [row_group_column]
      ]
    ),
    levels = unique(
      as.character(
        module_information[
          [row_group_column]
        ]
      )
    )
  )

  row_group_colors <- setNames(
    grDevices::hcl.colors(
      n = length(
        levels(
          row_groups
        )
      ),
      palette = "Dark 3"
    ),
    levels(
      row_groups
    )
  )

  left_annotation <- ComplexHeatmap::rowAnnotation(
    pathway = row_groups,
    col = list(
      pathway = row_group_colors
    ),
    show_annotation_name = FALSE
  )

  ComplexHeatmap::Heatmap(
    scaled_flux_matrix,
    name = "Row z-score",
    col = heatmap_color_function,
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    show_row_names = show_row_names,
    show_column_names = FALSE,
    row_names_gp = grid::gpar(
      fontsize = row_font_size
    ),
    row_split = row_groups,
    column_split = state_annotation$celltype,
    top_annotation = top_annotation,
    left_annotation = left_annotation,
    border = TRUE,
    use_raster = TRUE,
    raster_quality = 2,
    row_gap = grid::unit(
      1,
      "mm"
    ),
    column_gap = grid::unit(
      1,
      "mm"
    )
  )
}


archive_command_file <- function(
  command_file,
  output_table_dir
) {

  command_file <- trimws(
    as.character(
      command_file
    )
  )

  if (is.na(
    command_file
  ) ||
      command_file == "") {

    return(
      NA_character_
    )
  }

  if (!file.exists(
    command_file
  )) {

    warning(
      "The configured scFEA command file does not exist: ",
      command_file
    )

    return(
      NA_character_
    )
  }

  archived_file <- file.path(
    output_table_dir,
    paste0(
      "archived_scFEA_command.",
      tools::file_ext(
        command_file
      )
    )
  )

  file.copy(
    command_file,
    archived_file,
    overwrite = TRUE
  )

  archived_file
}


# 5. Define the per-analysis workflow ------------------------------------------

run_one_scfea_analysis <- function(
  manifest_row
) {

  analysis_id <- manifest_row$analysis_id[
    [1]
  ]

  analysis_id_safe <- sanitize_name(
    analysis_id
  )

  output_table_dir <- file.path(
    output_table_root,
    analysis_id_safe
  )

  output_figure_dir <- file.path(
    output_figure_root,
    analysis_id_safe
  )

  dir.create(
    output_table_dir,
    recursive = TRUE,
    showWarnings = FALSE
  )

  dir.create(
    output_figure_dir,
    recursive = TRUE,
    showWarnings = FALSE
  )

  message(
    "\nProcessing scFEA flux analysis: ",
    analysis_id
  )

  flux_matrix <- read_flux_matrix(
    flux_file = manifest_row$flux_file[
      [1]
    ],
    barcode_column = manifest_row$barcode_column[
      [1]
    ]
  )

  module_info <- read_module_information(
    manifest_row$module_info_file[
      [1]
    ]
  )

  flux_module_ids <- colnames(
    flux_matrix
  )

  missing_module_annotations <- setdiff(
    flux_module_ids,
    module_info$M_id
  )

  if (length(
    missing_module_annotations
  ) > 0) {

    stop(
      "The module-information file does not contain flux module(s): ",
      paste(
        missing_module_annotations,
        collapse = ", "
      )
    )
  }

  seurat_file <- manifest_row$seurat_file[
    [1]
  ]

  if (!file.exists(
    seurat_file
  )) {

    stop(
      "Seurat file does not exist: ",
      seurat_file
    )
  }

  object <- readRDS(
    seurat_file
  )

  if (!inherits(
    object,
    "Seurat"
  )) {

    stop(
      "The input RDS file does not contain a Seurat object."
    )
  }

  celltype_column <- manifest_row$celltype_column[
    [1]
  ]

  sample_column <- manifest_row$sample_column[
    [1]
  ]

  if (!celltype_column %in% colnames(
    object@meta.data
  )) {

    stop(
      "The Seurat metadata does not contain celltype column: ",
      celltype_column
    )
  }

  if (sample_column != "" &&
      !sample_column %in% colnames(
        object@meta.data
      )) {

    stop(
      "The Seurat metadata does not contain sample column: ",
      sample_column
    )
  }

  unmatched_barcodes <- setdiff(
    rownames(
      flux_matrix
    ),
    rownames(
      object@meta.data
    )
  )

  if (length(
    unmatched_barcodes
  ) > 0) {

    stop(
      "Some scFEA barcodes were not found in the Seurat metadata. Examples: ",
      paste(
        head(
          unmatched_barcodes,
          10
        ),
        collapse = ", "
      ),
      ". Ensure that the same sample prefixes and barcode format were used."
    )
  }

  matched_metadata <- object@meta.data[
    rownames(
      flux_matrix
    ),
    ,
    drop = FALSE
  ]

  cell_metadata <- tibble(
    barcode = rownames(
      flux_matrix
    ),
    celltype = as.character(
      matched_metadata[
        [celltype_column]
      ]
    )
  )

  if (sample_column != "") {

    cell_metadata$sample_id <- as.character(
      matched_metadata[
        [sample_column]
      ]
    )

  } else {

    cell_metadata$sample_id <- NA_character_
  }

  if (any(
    is.na(
      cell_metadata$celltype
    ) |
      cell_metadata$celltype == ""
  )) {

    stop(
      "Missing cell-state labels were detected after barcode matching."
    )
  }

  state_table <- read_state_annotations(
    manifest_row$state_annotation_file[
      [1]
    ]
  )

  selected_states <- state_table$celltype

  cells_in_selected_states <- cell_metadata$celltype %in%
    selected_states

  if (!any(
    cells_in_selected_states
  )) {

    stop(
      "None of the matched cells belonged to the configured cell states."
    )
  }

  excluded_states <- setdiff(
    unique(
      cell_metadata$celltype
    ),
    selected_states
  )

  if (length(
    excluded_states
  ) > 0) {

    message(
      "Excluding cell states not listed in the state-annotation file: ",
      paste(
        excluded_states,
        collapse = ", "
      )
    )
  }

  flux_matrix <- flux_matrix[
    cells_in_selected_states,
    ,
    drop = FALSE
  ]

  cell_metadata <- cell_metadata[
    cells_in_selected_states,
    ,
    drop = FALSE
  ]

  missing_configured_states <- setdiff(
    selected_states,
    unique(
      cell_metadata$celltype
    )
  )

  if (length(
    missing_configured_states
  ) > 0) {

    stop(
      "Configured cell states absent from the matched flux data: ",
      paste(
        missing_configured_states,
        collapse = ", "
      )
    )
  }

  write.csv(
    cell_metadata,
    file = file.path(
      output_table_dir,
      "scFEA_cell_metadata.csv"
    ),
    row.names = FALSE
  )

  write.csv(
    state_table,
    file = file.path(
      output_table_dir,
      "scFEA_state_annotations_used.csv"
    ),
    row.names = FALSE
  )


  # 5.1 Calculate mean flux by cell state --------------------------------------

  flux_with_metadata <- as.data.frame(
    flux_matrix,
    check.names = FALSE
  ) %>%
    rownames_to_column(
      "barcode"
    ) %>%
    left_join(
      cell_metadata,
      by = "barcode"
    )

  mean_flux_table <- flux_with_metadata %>%
    select(
      -barcode,
      -sample_id
    ) %>%
    group_by(
      celltype
    ) %>%
    summarise(
      across(
        everything(),
        ~ mean(
          .x,
          na.rm = TRUE
        )
      ),
      .groups = "drop"
    )

  mean_flux_table <- mean_flux_table[
    match(
      selected_states,
      mean_flux_table$celltype
    ),
    ,
    drop = FALSE
  ]

  mean_flux_matrix <- t(
    as.matrix(
      mean_flux_table[
        ,
        setdiff(
          colnames(
            mean_flux_table
          ),
          "celltype"
        ),
        drop = FALSE
      ]
    )
  )

  colnames(
    mean_flux_matrix
  ) <- mean_flux_table$celltype

  storage.mode(
    mean_flux_matrix
  ) <- "numeric"

  if (sample_column != "") {

    sample_flux_table <- flux_with_metadata %>%
      select(
        -barcode
      ) %>%
      group_by(
        sample_id,
        celltype
      ) %>%
      summarise(
        across(
          -sample_id,
          ~ mean(
            .x,
            na.rm = TRUE
          )
        ),
        .groups = "drop"
      )

    write.csv(
      sample_flux_table,
      file = file.path(
        output_table_dir,
        "scFEA_mean_flux_by_sample_and_celltype.csv"
      ),
      row.names = FALSE
    )

  } else {

    sample_flux_table <- NULL
  }


  # 5.2 Remove zero-variance modules -------------------------------------------

  module_sd <- apply(
    mean_flux_matrix,
    1,
    stats::sd,
    na.rm = TRUE
  )

  module_variance_table <- tibble(
    M_id = rownames(
      mean_flux_matrix
    ),
    standard_deviation = module_sd,
    retained = is.finite(
      module_sd
    ) &
      module_sd > 0
  )

  write.csv(
    module_variance_table,
    file = file.path(
      output_table_dir,
      "scFEA_module_variance_filter.csv"
    ),
    row.names = FALSE
  )

  retained_modules <- module_variance_table$M_id[
    module_variance_table$retained
  ]

  if (length(
    retained_modules
  ) == 0) {

    stop(
      "No metabolic modules remained after zero-variance filtering."
    )
  }

  mean_flux_matrix <- mean_flux_matrix[
    retained_modules,
    ,
    drop = FALSE
  ]


  # 5.3 Apply the reviewed metabolic-module order ------------------------------

  mean_flux_matrix <- apply_module_order(
    flux_matrix = mean_flux_matrix,
    module_info = module_info,
    module_order_file = manifest_row$module_order_file[
      [1]
    ]
  )

  retained_module_info <- module_info[
    match(
      rownames(
        mean_flux_matrix
      ),
      module_info$M_id
    ),
    ,
    drop = FALSE
  ]

  if (anyNA(
    retained_module_info$M_id
  )) {

    stop(
      "Some retained modules could not be matched to module information."
    )
  }

  plot_module_labels <- make_unique_module_labels(
    retained_module_info
  )

  full_plot_matrix <- mean_flux_matrix
  rownames(
    full_plot_matrix
  ) <- plot_module_labels

  full_scaled_matrix <- row_z_score(
    full_plot_matrix
  )

  retained_module_info$plot_label <- plot_module_labels

  write.csv(
    mean_flux_matrix,
    file = file.path(
      output_table_dir,
      "scFEA_mean_flux_by_celltype.csv"
    ),
    row.names = TRUE
  )

  write.csv(
    full_scaled_matrix,
    file = file.path(
      output_table_dir,
      "scFEA_mean_flux_by_celltype_row_zscore.csv"
    ),
    row.names = TRUE
  )

  write.csv(
    retained_module_info,
    file = file.path(
      output_table_dir,
      "scFEA_retained_module_information.csv"
    ),
    row.names = FALSE
  )


  # 5.4 Generate the full flux heatmap -----------------------------------------

  full_heatmap <- build_flux_heatmap(
    scaled_flux_matrix = full_scaled_matrix,
    module_information = retained_module_info,
    state_table = state_table,
    row_group_column = "SM_anno",
    show_row_names = TRUE,
    row_font_size = 4
  )

  save_complex_heatmap(
    heatmap_object = full_heatmap,
    output_dir = output_figure_dir,
    file_stem = "scFEA_flux_heatmap_full",
    width = manifest_row$full_heatmap_width[
      [1]
    ],
    height = manifest_row$full_heatmap_height[
      [1]
    ]
  )


  # 5.5 Generate the selected-module heatmap -----------------------------------

  selected_module_table <- read_external_table(
    file = manifest_row$selected_module_file[
      [1]
    ],
    required = FALSE
  )

  selected_flux_matrix <- NULL
  selected_scaled_matrix <- NULL
  selected_module_info <- NULL

  if (!is.null(
    selected_module_table
  )) {

    required_selected_columns <- c(
      "M_id",
      "pathway_group",
      "order"
    )

    missing_selected_columns <- setdiff(
      required_selected_columns,
      colnames(
        selected_module_table
      )
    )

    if (length(
      missing_selected_columns
    ) > 0) {

      stop(
        "The selected-module file is missing columns: ",
        paste(
          missing_selected_columns,
          collapse = ", "
        )
      )
    }

    selected_module_table <- selected_module_table %>%
      transmute(
        M_id = trimws(
          as.character(
            M_id
          )
        ),
        pathway_group = trimws(
          as.character(
            pathway_group
          )
        ),
        order = as.numeric(
          order
        ),
        pathway_color = if (
          "pathway_color" %in% colnames(
            selected_module_table
          )
        ) {
          trimws(
            as.character(
              selected_module_table$pathway_color
            )
          )
        } else {
          NA_character_
        }
      ) %>%
      arrange(
        order
      )

    if (anyDuplicated(
      selected_module_table$M_id
    )) {

      stop(
        "Duplicated M_id values were detected in the selected-module file."
      )
    }

    missing_selected_modules <- setdiff(
      selected_module_table$M_id,
      rownames(
        mean_flux_matrix
      )
    )

    if (length(
      missing_selected_modules
    ) > 0) {

      stop(
        "Selected modules are absent from the processed flux matrix: ",
        paste(
          missing_selected_modules,
          collapse = ", "
        )
      )
    }

    selected_flux_matrix <- mean_flux_matrix[
      selected_module_table$M_id,
      ,
      drop = FALSE
    ]

    selected_module_info <- retained_module_info[
      match(
        selected_module_table$M_id,
        retained_module_info$M_id
      ),
      ,
      drop = FALSE
    ]

    selected_module_info$pathway_group <-
      selected_module_table$pathway_group

    selected_module_info$pathway_color <-
      selected_module_table$pathway_color

    selected_labels <- make_unique_module_labels(
      selected_module_info
    )

    rownames(
      selected_flux_matrix
    ) <- selected_labels

    selected_module_info$plot_label <- selected_labels

    selected_scaled_matrix <- row_z_score(
      selected_flux_matrix
    )

    selected_pathway_levels <- unique(
      selected_module_info$pathway_group
    )

    selected_pathway_colors <- selected_module_info %>%
      distinct(
        pathway_group,
        pathway_color
      )

    missing_pathway_colors <- is.na(
      selected_pathway_colors$pathway_color
    ) |
      selected_pathway_colors$pathway_color == ""

    generated_colors <- grDevices::hcl.colors(
      n = sum(
        missing_pathway_colors
      ),
      palette = "Dark 3"
    )

    selected_pathway_colors$pathway_color[
      missing_pathway_colors
    ] <- generated_colors

    selected_pathway_color_vector <- setNames(
      selected_pathway_colors$pathway_color,
      selected_pathway_colors$pathway_group
    )

    state_order <- state_table$celltype

    state_annotation <- data.frame(
      subcelltype = factor(
        state_table$celltype,
        levels = state_order
      ),
      celltype = factor(
        state_table$broad_celltype,
        levels = unique(
          state_table$broad_celltype
        )
      ),
      row.names = state_order,
      check.names = FALSE
    )

    state_colors <- setNames(
      state_table$state_color,
      state_table$celltype
    )

    broad_colors_table <- state_table %>%
      distinct(
        broad_celltype,
        broad_color
      )

    broad_colors <- setNames(
      broad_colors_table$broad_color,
      broad_colors_table$broad_celltype
    )

    top_annotation <- ComplexHeatmap::HeatmapAnnotation(
      df = state_annotation,
      col = list(
        subcelltype = state_colors,
        celltype = broad_colors
      ),
      show_annotation_name = FALSE
    )

    selected_groups <- factor(
      selected_module_info$pathway_group,
      levels = selected_pathway_levels
    )

    left_annotation <- ComplexHeatmap::rowAnnotation(
      pathway = selected_groups,
      col = list(
        pathway = selected_pathway_color_vector
      ),
      show_annotation_name = FALSE
    )

    selected_heatmap <- ComplexHeatmap::Heatmap(
      selected_scaled_matrix,
      name = "Row z-score",
      col = heatmap_color_function,
      cluster_rows = FALSE,
      cluster_columns = FALSE,
      show_row_names = TRUE,
      show_column_names = FALSE,
      row_split = selected_groups,
      column_split = state_annotation$celltype,
      top_annotation = top_annotation,
      left_annotation = left_annotation,
      border = TRUE,
      use_raster = TRUE,
      raster_quality = 2,
      row_gap = grid::unit(
        1,
        "mm"
      ),
      column_gap = grid::unit(
        1,
        "mm"
      )
    )

    save_complex_heatmap(
      heatmap_object = selected_heatmap,
      output_dir = output_figure_dir,
      file_stem = "scFEA_flux_heatmap_selected_modules",
      width = manifest_row$selected_heatmap_width[
        [1]
      ],
      height = manifest_row$selected_heatmap_height[
        [1]
      ]
    )

    write.csv(
      selected_flux_matrix,
      file = file.path(
        output_table_dir,
        "scFEA_selected_module_mean_flux.csv"
      ),
      row.names = TRUE
    )

    write.csv(
      selected_scaled_matrix,
      file = file.path(
        output_table_dir,
        "scFEA_selected_module_mean_flux_row_zscore.csv"
      ),
      row.names = TRUE
    )

    write.csv(
      selected_module_info,
      file = file.path(
        output_table_dir,
        "scFEA_selected_module_annotations.csv"
      ),
      row.names = FALSE
    )
  }


  # 5.6 Save the processed result bundle ---------------------------------------

  result_bundle <- list(
    analysis_id = analysis_id,
    cell_metadata = cell_metadata,
    mean_flux_by_celltype = mean_flux_matrix,
    mean_flux_by_celltype_row_zscore = full_scaled_matrix,
    mean_flux_by_sample_and_celltype = sample_flux_table,
    retained_module_information = retained_module_info,
    selected_module_mean_flux = selected_flux_matrix,
    selected_module_mean_flux_row_zscore = selected_scaled_matrix,
    selected_module_information = selected_module_info,
    state_annotations = state_table
  )

  if (manifest_row$save_per_cell_flux[
    [1]
  ]) {

    result_bundle$flux_per_cell <- flux_matrix
  }

  output_bundle_file <- file.path(
    output_data_root,
    paste0(
      analysis_id_safe,
      "_scFEA_postprocessing.rds"
    )
  )

  saveRDS(
    result_bundle,
    file = output_bundle_file,
    compress = "gzip"
  )

  archived_command_file <- archive_command_file(
    command_file = manifest_row$scfea_command_file[
      [1]
    ],
    output_table_dir = output_table_dir
  )


  # 5.7 Save analysis parameters ----------------------------------------------

  analysis_parameters <- tibble(
    parameter = c(
      "analysis_id",
      "flux_file",
      "barcode_column",
      "module_info_file",
      "seurat_file",
      "celltype_column",
      "sample_column",
      "state_annotation_file",
      "module_order_file",
      "selected_module_file",
      "archived_scFEA_command_file",
      "flux_summary",
      "heatmap_scaling",
      "column_clustering",
      "row_clustering",
      "n_matched_cells",
      "n_cell_states",
      "n_input_modules",
      "n_retained_modules",
      "n_selected_modules",
      "save_per_cell_flux"
    ),
    value = c(
      analysis_id,
      manifest_row$flux_file[
        [1]
      ],
      manifest_row$barcode_column[
        [1]
      ],
      manifest_row$module_info_file[
        [1]
      ],
      seurat_file,
      celltype_column,
      sample_column,
      manifest_row$state_annotation_file[
        [1]
      ],
      manifest_row$module_order_file[
        [1]
      ],
      manifest_row$selected_module_file[
        [1]
      ],
      archived_command_file,
      "Arithmetic mean across cells within each configured cell state",
      "Row-wise z-score across configured cell states",
      "Disabled",
      "Disabled",
      as.character(
        nrow(
          cell_metadata
        )
      ),
      as.character(
        length(
          selected_states
        )
      ),
      as.character(
        ncol(
          flux_matrix
        )
      ),
      as.character(
        nrow(
          mean_flux_matrix
        )
      ),
      if (
        is.null(
          selected_flux_matrix
        )
      ) {
        "0"
      } else {
        as.character(
          nrow(
            selected_flux_matrix
          )
        )
      },
      as.character(
        manifest_row$save_per_cell_flux[
          [1]
        ]
      )
    )
  )

  write.csv(
    analysis_parameters,
    file = file.path(
      output_table_dir,
      "scFEA_postprocessing_parameters.csv"
    ),
    row.names = FALSE
  )

  tibble(
    analysis_id = analysis_id,
    status = "completed",
    flux_file = manifest_row$flux_file[
      [1]
    ],
    n_matched_cells = nrow(
      cell_metadata
    ),
    n_cell_states = length(
      selected_states
    ),
    n_input_modules = ncol(
      flux_matrix
    ),
    n_retained_modules = nrow(
      mean_flux_matrix
    ),
    n_selected_modules = if (
      is.null(
        selected_flux_matrix
      )
    ) {
      0L
    } else {
      nrow(
        selected_flux_matrix
      )
    },
    output_bundle_file = output_bundle_file
  )
}


# 6. Load and validate the analysis manifest -----------------------------------

if (!file.exists(
  manifest_file
)) {

  stop(
    "scFEA manifest does not exist: ",
    manifest_file,
    "\nCreate it from the provided template before running this script."
  )
}

analysis_manifest <- read.csv(
  manifest_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

analysis_manifest <- validate_manifest(
  analysis_manifest
)


# 7. Run all configured scFEA analyses -----------------------------------------

analysis_results <- vector(
  mode = "list",
  length = nrow(
    analysis_manifest
  )
)

for (i in seq_len(
  nrow(
    analysis_manifest
  )
)) {

  current_analysis_id <- analysis_manifest$analysis_id[
    [i]
  ]

  analysis_results[
    [i]
  ] <- tryCatch(
    run_one_scfea_analysis(
      analysis_manifest[
        i,
        ,
        drop = FALSE
      ]
    ),
    error = function(e) {

      message(
        "scFEA analysis failed: ",
        current_analysis_id,
        "\nReason: ",
        conditionMessage(
          e
        )
      )

      tibble(
        analysis_id = current_analysis_id,
        status = "failed",
        flux_file = analysis_manifest$flux_file[
          [i]
        ],
        n_matched_cells = NA_integer_,
        n_cell_states = NA_integer_,
        n_input_modules = NA_integer_,
        n_retained_modules = NA_integer_,
        n_selected_modules = NA_integer_,
        output_bundle_file = NA_character_,
        error_message = conditionMessage(
          e
        )
      )
    }
  )
}

analysis_summary <- bind_rows(
  analysis_results
)

write.csv(
  analysis_summary,
  file = file.path(
    output_table_root,
    "09_scFEA_analysis_summary.csv"
  ),
  row.names = FALSE
)


# 8. Save software information -------------------------------------------------

writeLines(
  capture.output(
    sessionInfo()
  ),
  con = file.path(
    output_table_root,
    "09_scFEA_postprocessing_sessionInfo.txt"
  )
)

message(
  "Configured scFEA flux post-processing analyses have finished."
)

print(
  analysis_summary
)
